//------------------------------------------------------------------------------
// <auto-generated>
//     本文件代码自动生成。用于实现强类型接口，方便应用层使用。
//     版本号:1.7.0
//
//     请勿修改，否则在重新生成时，所有修改会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using Rafy;
using Rafy.ComponentModel;
using Rafy.Data;
using Rafy.Domain;
using Rafy.Domain.ORM;

namespace $domainNamespace$
{
    //partial class $domainEntityName$List
    //{
    //    #region 强类型公有接口

    //    /// <summary>
    //    /// 获取或设置指定位置的实体。
    //    /// </summary>
    //    /// <param name="index"></param>
    //    /// <returns></returns>
    //    public new $domainEntityName$ this[int index]
    //    {
    //        get
    //        {
    //            return base[index] as $domainEntityName$;
    //        }
    //        set
    //        {
    //            base[index] = value;
    //        }
    //    }

    //    /// <summary>
    //    /// 获取本实体列表的迭代器。
    //    /// </summary>
    //    /// <returns></returns>
    //    [DebuggerStepThrough]
    //    public new IEnumerator<$domainEntityName$> GetEnumerator()
    //    {
    //        return new EntityListEnumerator<$domainEntityName$>(this);
    //    }

    //    /// <summary>
    //    /// 返回子实体的强类型迭代接口，方便使用 Linq To Object 操作。
    //    /// </summary>
    //    /// <returns></returns>
    //    [DebuggerStepThrough]
    //    public $concreteNew$IEnumerable<$domainEntityName$> Concrete()
    //    {
    //        return this.Cast<$domainEntityName$>();
    //    }

    //    #endregion
    //}$repositoryAutoCode$
}