//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rafy.LicenseManager.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LicenseManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseManagerResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rafy.LicenseManager.Properties.LicenseManagerResource", typeof(LicenseManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已经复制到剪贴版，请在编辑器中按 Ctrl + V 进行粘贴。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormdgvContextMenuPaste {
            get {
                return ResourceManager.GetString("ManagerFormdgvContextMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权目标错误。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormGetLicenseEntityAuthenticationTargetWarning {
            get {
                return ResourceManager.GetString("ManagerFormGetLicenseEntityAuthenticationTargetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成授权码成功，已放入剪贴板。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormSaveLicenseSuccess {
            get {
                return ResourceManager.GetString("ManagerFormSaveLicenseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在“获取私钥”选项卡生成或输入公钥与私钥。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormServiceValidateParametersNeedPrivateKeyAndPublicKey {
            get {
                return ResourceManager.GetString("ManagerFormServiceValidateParametersNeedPrivateKeyAndPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权信息查询 的本地化字符串。
        /// </summary>
        internal static string ManagerFormTabControl1SelectedQueryAuthentication {
            get {
                return ResourceManager.GetString("ManagerFormTabControl1SelectedQueryAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期时间不能小于当前时间。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormValidateParametersExpireTime {
            get {
                return ResourceManager.GetString("ManagerFormValidateParametersExpireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC 地址不能为空或格式错误。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormValidateParametersMACAddress {
            get {
                return ResourceManager.GetString("ManagerFormValidateParametersMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 MAC 地址：{0}，已经被授权。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormValidateParametersMACHasUsed {
            get {
                return ResourceManager.GetString("ManagerFormValidateParametersMACHasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择授权目标。 的本地化字符串。
        /// </summary>
        internal static string ManagerFormValidateParametersSelectAuthenticationTarget {
            get {
                return ResourceManager.GetString("ManagerFormValidateParametersSelectAuthenticationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string ManagerFormValidateParametersWarning {
            get {
                return ResourceManager.GetString("ManagerFormValidateParametersWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;RSAKeyValue&gt;&lt;Modulus&gt;okAzI6fj05hiksTd/uXpuZf5mK98flQzFbHo2gE/w3GdFxdwbXVgknd443N+vz4NGwZQyeo3nq3WDBad9PEtmJlzrSPU5R5uEkYjAcTktM12CmKSC+csmbEZUuoFq7rMdWGclsQ03p7bS6Go2nFVZApp3BFhgStUTFG5oCHHJrE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;40afsMjClbFG3mMrH5K2Y2lP1VJ7xBeXlGDE3mocs5RiTo0n97E9nCnIfoOC24T61a6uRzY0ykVuZRbEUJ17FQ==&lt;/P&gt;&lt;Q&gt;tsG6Q+LTQGEiDE1DLp6hswN+7grNLuNYKgrSTQ+v45r778vVMlWF3IwCdMQ4meoBthkxzqKeLc/UHMLDecd0LQ==&lt;/Q&gt;&lt;DP&gt;VE4AMl1mAIzv0tJKTr3nNdz8pg6gpk5yBbIXlMEbwGlMRgMKTlDKn8DIBFXYFoGvYdAYCYZL8rPqjUjyrUydOQ==&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;RSAKeyValue&gt;&lt;Modulus&gt;okAzI6fj05hiksTd/uXpuZf5mK98flQzFbHo2gE/w3GdFxdwbXVgknd443N+vz4NGwZQyeo3nq3WDBad9PEtmJlzrSPU5R5uEkYjAcTktM12CmKSC+csmbEZUuoFq7rMdWGclsQ03p7bS6Go2nFVZApp3BFhgStUTFG5oCHHJrE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt; 的本地化字符串。
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
    }
}
